//! Machine-readable command manifest, emitted by `deck --json --help`.
//!
//! The manifest is generated by walking the clap command graph, so its
//! coverage cannot drift from the real parser: every command, positional,
//! option, and description comes from the same definitions that generate
//! `--help`. The only hand-maintained piece is the output-type annotation
//! per command, and a unit test fails when a command is missing one.

use anyhow::Result;
use clap::CommandFactory;
use serde::Serialize;

use crate::contracts::print_json;

#[derive(Debug, Serialize)]
struct ManifestEntry {
    argv: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    options: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    about: Option<String>,
    output: &'static str,
}

pub fn print_manifest() -> Result<()> {
    let root = built_command();
    let mut commands = serde_json::Map::new();
    for (path, command) in leaf_commands(&root) {
        let key = path.join("_").replace('-', "_");
        commands.insert(key, serde_json::to_value(entry(command, &path))?);
    }
    print_json(&serde_json::json!({
        "name": "deck",
        "version": env!("CARGO_PKG_VERSION"),
        "json": {
            "flag": "--json",
            "scope": "global: every command accepts it and prints structured JSON",
            "errors": "failures use the JsonError envelope and a nonzero exit code",
            "failed_runs": "run/workflow/sandbox failures print one result document with ok=false and exit nonzero",
            "manifest": "this document; emitted by deck --json --help"
        },
        "commands": commands,
        "json_error": {
            "output": "JsonError",
            "shape": {
                "ok": false,
                "error": {
                    "kind": "string",
                    "message": "string"
                }
            }
        }
    }))
}

/// The clap command graph with defaults materialized. `CommandFactory::command`
/// alone leaves per-arg defaults (like `num_args`) unset until `build` runs.
fn built_command() -> clap::Command {
    let mut root = crate::cli::Args::command();
    root.build();
    root
}

/// All runnable leaf commands with their subcommand paths, in clap order.
fn leaf_commands(root: &clap::Command) -> Vec<(Vec<String>, &clap::Command)> {
    let mut leaves = Vec::new();
    collect_leaves(root, &mut Vec::new(), &mut leaves);
    leaves
}

fn collect_leaves<'a>(
    command: &'a clap::Command,
    path: &mut Vec<String>,
    leaves: &mut Vec<(Vec<String>, &'a clap::Command)>,
) {
    for sub in command.get_subcommands() {
        if sub.get_name() == "help" {
            continue;
        }
        path.push(sub.get_name().to_string());
        if sub.has_subcommands() {
            collect_leaves(sub, path, leaves);
        } else {
            leaves.push((path.clone(), sub));
        }
        path.pop();
    }
}

fn entry(command: &clap::Command, path: &[String]) -> ManifestEntry {
    let mut argv = vec!["deck".to_string()];
    argv.extend(path.iter().cloned());
    argv.extend(command.get_positionals().map(positional_shape));
    let options = command
        .get_arguments()
        .filter(|arg| !arg.is_positional())
        .filter(|arg| !matches!(arg.get_id().as_str(), "help" | "version" | "json"))
        .map(option_shape)
        .collect();
    ManifestEntry {
        argv,
        options,
        about: command.get_about().map(|about| about.to_string()),
        output: output_type(&path.join(" ")).unwrap_or("unknown"),
    }
}

fn positional_shape(arg: &clap::Arg) -> String {
    let mut name = value_name(arg);
    if arg
        .get_num_args()
        .is_some_and(|range| range.max_values() > 1)
    {
        name.push_str("..");
    }
    if arg.is_required_set() {
        name
    } else {
        format!("[{name}]")
    }
}

fn option_shape(arg: &clap::Arg) -> String {
    let flag = arg.get_long().map_or_else(
        || format!("-{}", arg.get_short().unwrap_or('?')),
        |long| format!("--{long}"),
    );
    if !arg.get_num_args().is_some_and(|range| range.takes_values()) {
        return flag;
    }
    let possible = arg.get_possible_values();
    let value = if possible.is_empty() {
        value_name(arg)
    } else {
        possible
            .iter()
            .map(|value| value.get_name().to_string())
            .collect::<Vec<_>>()
            .join("|")
    };
    format!("{flag} <{value}>")
}

fn value_name(arg: &clap::Arg) -> String {
    arg.get_value_names()
        .and_then(|names| names.first())
        .map(|name| name.to_string())
        .unwrap_or_else(|| arg.get_id().to_string().to_uppercase())
}

/// Output type per command path. Coverage is enforced by the unit test below:
/// adding a CLI command without an annotation here fails the build gate.
fn output_type(path: &str) -> Option<&'static str> {
    Some(match path {
        "scan" => "ScanJson",
        "list" => "ProjectListItem[]",
        "commands" => "ProjectCommands[]",
        "run" | "rerun" => "RunJson or CommandPlan",
        "start" | "stop" | "restart" => "ProcessActionJson",
        "ps" => "ProcessJson[]",
        "logs" => "LogsJson",
        "git" | "docker" | "gh issues" | "search" | "ssh-hosts" | "journal" => "ToolOutputJson",
        "workflow list" => "ProjectWorkflows",
        "workflow run" => "WorkflowRunJson or WorkflowPlan",
        "plugin add" | "plugin add-path" | "plugin remove" => "PluginRegistryJson",
        "plugin list" => "ProjectPlugins or PluginSpec[]",
        "plugin manifest" | "plugin panels" | "plugin actions" => {
            "plugin protocol JSON (always JSON)"
        }
        "plugin run" => "PluginRunJson",
        "context" => "ContextBundle",
        "status" => "ProjectStatus[]",
        "summary" => "SummaryJson",
        "sandbox plan" => "SandboxPlanJson",
        "sandbox run" => "SandboxRunJson",
        "sandbox doctor" => "SandboxDoctorJson",
        "tasks list" => "TaskListJson",
        "tasks add" | "tasks set" | "tasks remove" => "ConfigEditJson",
        "config apply"
        | "config add-command"
        | "config add-argv-command"
        | "config remove-command"
        | "config add-workflow"
        | "config remove-workflow"
        | "config add-plugin"
        | "config add-plugin-path"
        | "config remove-plugin"
        | "config add-sandbox"
        | "config remove-sandbox" => "ConfigEditJson",
        "recent" => "RecentJson",
        "init" => "InitJson",
        "clear-runs" => "ClearRunsJson",
        "tui" => "none (interactive TUI)",
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_leaf_command_has_an_output_annotation() {
        let root = built_command();
        let missing = leaf_commands(&root)
            .into_iter()
            .map(|(path, _)| path.join(" "))
            .filter(|path| output_type(path).is_none())
            .collect::<Vec<_>>();
        assert!(
            missing.is_empty(),
            "commands missing a manifest output annotation: {missing:?}"
        );
    }

    #[test]
    fn shapes_render_positionals_and_options() {
        let root = built_command();
        let leaves = leaf_commands(&root);
        let (path, run) = leaves
            .iter()
            .find(|(path, _)| path == &["run".to_string()])
            .unwrap();
        let rendered = entry(run, path);
        assert_eq!(rendered.argv, ["deck", "run", "PROJECT", "COMMAND"]);
        assert!(rendered.options.contains(&"--dry-run".to_string()));
    }
}
